databaseChangeLog:
  - changeSet:
      id: 20180823040901
      author: jhipster
      changes:
        - createTable:
            tableName: version
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: version
                  type: varchar(255)
                  constraints:
                    nullable: true
        - loadData:
              encoding: UTF-8
              file: config/liquibase/version.csv
              separator: ;
              tableName: version
